### ISSUE TITLE
Thinking of dropping Mac support

### ISSUE THREAD

**Issue by capr** [luapower/support#10]
Here's the thing: since the new M1 Macs, in order to keep saying that luapower works on Mac, I would have to support a new platform and build all binary packages for that. Building for M1 sucks: I'll either have to buy a new Mac or cross-compile from an Intel Mac and not have a chance to test the binary to see if it actually works. So I won't be able to answer support questions related to M1. Also, I'm tired of buying Macs for the sole purpose of supporting luapower since I don't have other uses for a Mac myself. Also, Apple has no sizeable market on the desktop, heck half of it is probably google devs skewing the statistics. Also, I'd have to make the sock module work on Mac (i.e. implement kqueue) which I will probably never use myself ever, unless I get a client who desperately needs a networked desktop app for Mac (fat chance -- or I'll probably use swift). All in all, seems like my life will improve by dropping OSX support altogheter, unless someone else wants to maintain that. I'll keep this open for a month and then make the necessary changes on the website.

**Comment by PhilMo6** [comment]
Do it! Sometimes making ones life easier is a priority.

**Comment by capr** [comment]
Done. Binaries, build scripts and Lua modules related to Mac OS were _not_ removed from the repos since most of them work fine right now, so I'll just leave them to entropy.
