### ISSUE TITLE
any luafilesystem like packages?

### ISSUE THREAD

**Issue by PhilMo6** [luapower/support#11]
I need to scan the contents of directorys on windows and was curious if there is a luapower package that lets me do that or if i should try lfs? Iv sorta hacked up one with popen but its iffy.

**Comment by capr** [comment]
Yes, see http://luapower.com/fs

**Comment by PhilMo6** [comment]
Ah sweet, I knew I was missing something obvious! You've pretty thoroughly covered including a lot of the basic stuff like that.
