### ISSUE TITLE
trying to use the http module

### ISSUE THREAD

**Issue by PhilMo6** [luapower/support#12]
when I require the http module I get the following error
luajit: D:\gcc-lua\luapower\bin\mingw64\..\..\http.lua:8: module 'stream' not found:
Is this stream module supposed to be included in the luapower install?

**Comment by capr** [comment]
Maybe you have an older version? I removed the stream module a long time ago.

**Comment by PhilMo6** [comment]
I just updated the http module from the most recent github and now im getting
http.lua:10: module 'linebuffer' not found:

**Comment by capr** [comment]
Looks like you caught a missing dependency. Sorry about that, fixed.

If you're using mgit: `mgit clone luapower/linebuffer`, or you can get it from here https://github.com/luapower/linebuffer

**Comment by PhilMo6** [comment]
Sweet sauce now it requires just fine! Now to figure out how to make this https request for the youtube api!

**Comment by capr** [comment]
Unfortunately the http client needs a little love, I've only been using the server for the past 6 months. Lemme run some tests and see if anything needs fixing. Oh, and TLS is not working at the moment. I should've worked on a separate branch so you can have master always in the stable state but I was git-lazy since I don't really know if anyone is using these libraries so I'm mainly just working on them for myself.

**Comment by PhilMo6** [comment]
ah well thats unfortunate but that'll happen lol. I could probably use luasec and figure it out. I only need it to make a quick call the the youtube api to grab some json data but its gotta be through ssl.

**Comment by capr** [comment]
Ya I hear you. Well anyway I'll fix the client and put a `http_client_test.lua` in there and swear not to work on master on stable modules anymore :)

In the meantime you can always use the trusty https://luapower.com/libcurl (make sure to have luapower/zlib and luapower/openssl too)

**Comment by PhilMo6** [comment]
Huh I did not know that was an option. I will have to check that out!

**Comment by PhilMo6** [comment]
So I don't want to make a new issue for this so ill ask here. Using libcurl I get the response I want back from the youtube api but its just printed to the console and im having trouble figuring out how to actually access it from the easy transfer object.

**Comment by capr** [comment]
It's the `writefunction` option. Look at `libcurl_test.lua` for details.

**Comment by PhilMo6** [comment]
Alright that did it! Was obvious when I looked at it lol. Covid brain is a thing, Its like my brains working at have pace right now.
