### ISSUE TITLE
`fs` named pipes

### ISSUE THREAD

**Issue by cpkio** [luapower/support#8]
I find it hard to understand how to create a named pipe in Windows/Neovim environment. The `fs.pipe({ path = [[\\.\pipe\neovimpipe]], opt = { timeout = 1000}})` call returns `nil` with a `87` error code («out_of_mem» error text of yours is displayed for some reason, but it's ok), which means `CreateNamedPipeW` has got an invalid parameter.

Could you please give a example of a correct pipe call?

**Comment by capr** [comment]
Hi, give options directly like {path=, timeout=}

**Comment by cpkio** [comment]
Sorry, this was so simple to fix… Thanks for your great project.
