### ISSUE TITLE
New to Lua and LuaJit

### ISSUE THREAD

**Issue by WeLua** [luapower/support#9]
Hi,
I have two questions:

I read the "Swedish buffet" on the luapower website.
Under 'Databases', only mysql is mentioned.
Is Sqlite not supported?

I also read that the oldest windows supported is Win7_64bit.
Does that mean the Win7_32bit is not supported?

**Comment by capr** [comment]
Hi, yes there's no sqlite lib. 32bit support was dropped a long time ago but you can still build for 32bit if you really want

**Comment by WeLua** [comment]
Thanks for the quick response!

Good to know that 32bit is still possible. 

For sqlite:
I found "SQLite/LuaJIT binding" on https://github.com/tami5/sqlite.lua

Would that mean that it is possible to connect Luajit to sqlite? But not via Luapower?
Or do you think that tami5 mixes up Lua and Luajit?

**Comment by capr** [comment]
luapower is just a bunch of libraries, there's nothing preventing you to use other libraries with the luapower libraries

**Comment by WeLua** [comment]
Ok, thanks for the info!
